### ISSUE TITLE
Authentifier un etudiant

### ISSUE THREAD

**Issue by Tescar** [Tescar/WeTheBest-ValEtu#1]
En tant qu'ÉTUDIANT, je veux m'AUTHENTIFIER afin d'accéder de façon sécuritaire à ValEtu et faire valider mon paiement des frais de scolarité.

Pré-conditions: 
- L'étudiant est préalablement inscrit a l'INUKA.
- L'étudiant doit inscrire dans le système ValEtu

Déclencheur: L'Étudiant clique sur le bouton "Demarrer"

Déroulement:
1. ValEtu affiche la page d'authentification:
- Code du dossier étudiant (seulement les 5 derniers chiffres): format 99999 
- Pseudo de l’étudiant (un surnom de l’étudiant ou nom d’emprunt  pour cacher sa véritable identité)
- Un mot de passe (Ce mot de passe a été générer par l’application Lors de l’inscription).

**Règles d’affaires : **
Champs obligatoires: 
- Si _champs vides_ --> ValEtu affichera un message <<Veuillez remplir tous les champs >>
-  Si _Pseudo incorrect_ --> ValEtu affichera un message "informations incorrectes"
- Si _mot de passe incorrect_ --> ValEtu affichera un message  "pseudo ou mot de passe incorrect" 
- Si _code étudiant   n’existe pas_ --> le système affichera un message d’erreur<< code non trouvé>>

**Comment by CharlesEvens** [comment]
J'ai lu le document,  j'ai ajouté ce qui manquait

**Comment by Tescar** [comment]
Quelques corrections apportées

**Comment by strudelauxpommes** [comment]
Liste des cas de test:
1. Authentification réussie --> La page d'accueil s'affiche.
1.  champs vides --> ValEtu affichera un message <Veuillez remplir tous les champs>
1.  Pseudo incorrect --> ValEtu affichera un message "pseudo ou mot de passe incorrect"
1.  mot de passe incorrect --> ValEtu affichera un message "pseudo ou mot de passe incorrect"
1.  code étudiant n’existe pas --> le système affichera un message d’erreur<<code non trouvé>>
